<a href="https://colab.research.google.com/github/gabrielasenareis/python-basico/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [66]:
import numpy as np

lista = np.array([0,1,2,3,4,5])

print(lista)
print(type(lista))
print('-----------------')
# definindo um tipo usando numpy

lista1 = np.array([1,2,3,4,5], dtype = np.int32)
print(lista1, type(lista))
print('-----------------')
lista2 = np.array([1,2,3,4,5], dtype = np.float64)
print(lista2, type(lista))
print('-----------------')
# modificando um tipo
lista2 = lista2.astype(np.int32)
print(lista2)
print('-----------------')

# criando matrizes unidimensionais e bidimensionais
array1 = np.arange(8)
print(array1)
print('-----------------')
array2= np.arange(8).reshape((2,4))
print(array2)
print('-----------------')
# criando matrizes bidimensionais e mostrando o seu tamanho
matriz = np.array([[1,2,3,4], [1,2,3,4],[1,2,3,4], [1,2,3,4]])
print(matriz)
print(matriz[2,3])
print(matriz.shape)
print('-----------------')
# criando matrizes vazias

matrizempty = np.empty([2,5], dtype = int)
print(matrizempty)
print('-----------------')

# criando matrizes com "zero" e "um"

zeros = np.zeros([2,5], dtype = int)
print(zeros)
print('-----------------')
uns = np.ones([2,5], dtype = int)
print(uns)
print('-----------------')

# criando matriz quadrada com a diagonal de "um"

diagonal = np.eye(4, dtype = float)
print(diagonal)
print('-----------------')
# números aleatorios, com distribuição normal contendo negativos

aleatorio = np.random.random((5))
print(aleatorio)
print('-----------------')
aleatorio2 = np.random.randn(5,5)
print(aleatorio2)
print('-----------------')
# para obter números maiores ou inteiros multiplica por 10 ou
# usa o método numpy.random.randint()

aleatorio3 = (10*np.random.random((3,3)))
print(aleatorio3)
print('-----------------')

aleatorio4 = np.random.randint(0,9,(5,5))
print(aleatorio4)
print('-----------------')


# uso de semente para guardar valores aleatórios
semente = np.random.default_rng(1)
aleatorio5 = semente.random(4)
print(aleatorio5)
print('-----------------')
# para gerar inteiros:
aleatorio6 = semente.integers(10, size = (3,4))
print(aleatorio6)
print('-----------------')
# método unique para remover repetições

repetidos = np.array([1,1,1,1,2,2,2,2,3,3,3,3])
repetidos = np.unique(repetidos)
print(repetidos)
print('-----------------')
# funções matemáticas:
# respectivamente, maior e menor valor de uma matriz, soma dos valores, valor
# da média, valor do desvio padrão e raiz quadrada

print(matriz.max())
print(matriz.min())
print(matriz.sum())
print(matriz.mean())
print(matriz.std())
print(np.sqrt(matriz))

# mostrando em posições diferentes na matriz:

print(matriz[0])
print('-----------------')
#mostrando a partir da posição "2", até o final
print(matriz[2:])
print('-----------------')
#mostrando a partir da ultima posição , até o final
print(matriz[-2:])
print('-----------------')

# extração de linhas e colunas:

matrizz = np.array([[1,2,3], [4,5,6], [7,8,9]])
# exibindo primeira linha e todas as colunas
linha1 = matrizz[0, : ]
print(linha1)
print('-----------------')
# exibindo segunda linha e todas as colunas
linha2 = matrizz[1, : ]
print(linha2)
print('-----------------')
# exibindo todas as linhas, primeira coluna
coluna1 = matrizz[ :, 0 ]
print(coluna1)
print('-----------------')
# exibindo todas as linhas, segunda coluna
coluna2 = matrizz[ :, 1 ]
print(coluna2)
print('-----------------')
# adição e multiplicaçao de matrizes
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
b = np.array([[1,1,1],[1,1,1],[1,1,1]])
soma = a+b
multip = a*b
print(soma)
print('-----------------')
print(multip)
print('-----------------')
c = np.array([[2,2,3]])
soma2 = a+c
print(soma2)
print('-----------------')

# transpostando as linhas em colunas
trans = np.array([[1,1,1],[2,2,2],[3,3,3],[4,4,4]])
print(trans)
print('-----------------')
trans2 = trans.T
print(trans2)
print('-----------------')
# expressões lógicas
arrayaleatorio = (10*np.random.randn(5,5))
print(arrayaleatorio)
print('-----------------')
booleano = arrayaleatorio > 0
print(booleano)
print('-----------------')
# usando where (sea expressão for verdadeira imprime primeiro o valor
# se for falso imprime o segundo valor)

z = np.where(arrayaleatorio > 0, 1, -1)
print(z)

[0 1 2 3 4 5]
<class 'numpy.ndarray'>
-----------------
[1 2 3 4 5] <class 'numpy.ndarray'>
-----------------
[1. 2. 3. 4. 5.] <class 'numpy.ndarray'>
-----------------
[1 2 3 4 5]
-----------------
[0 1 2 3 4 5 6 7]
-----------------
[[0 1 2 3]
 [4 5 6 7]]
-----------------
[[1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]]
4
(4, 4)
-----------------
[[1 1 1 1 1]
 [1 1 1 1 1]]
-----------------
[[0 0 0 0 0]
 [0 0 0 0 0]]
-----------------
[[1 1 1 1 1]
 [1 1 1 1 1]]
-----------------
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
-----------------
[0.60715545 0.39157518 0.80295029 0.60332839 0.57118312]
-----------------
[[-0.07112439 -0.40153774  1.16722349  1.06559838  0.27293632]
 [ 0.89639013 -1.58111399  2.09525369  0.42811952 -1.37143113]
 [-0.02956206 -0.66380889 -0.65751135  1.3992379  -1.3858964 ]
 [-1.33335101  0.33780027  0.46340826  1.77718621 -0.37851623]
 [-1.14942772  1.50732606  1.8909468  -1.63023872 -0.27179506]]
-----------------
[[5.24238884 2.39895352 1.037